apiVersion: v1
kind: Service
metadata:
  name: service-workflow
  labels:
    app: service-workflow
spec:
  type: ClusterIP
  selector:
    app: service-workflow
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
